// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC9hMRr5ngywA3MjJvv4us4MCIX8HsRYo',
    appId: '1:229887506217:web:ac2f88cf369d477e692938',
    messagingSenderId: '229887506217',
    projectId: 'event-manager-12814',
    authDomain: 'event-manager-12814.firebaseapp.com',
    storageBucket: 'event-manager-12814.appspot.com',
    measurementId: 'G-84Y0KSK8W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-DtvUNN5z-9EVgp6B7ZHfq2Op4mSjrdk',
    appId: '1:229887506217:android:bcc38ffef024fcb8692938',
    messagingSenderId: '229887506217',
    projectId: 'event-manager-12814',
    storageBucket: 'event-manager-12814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRNe88o9px3VMC7FufwJsDZhqlRQZLUtw',
    appId: '1:229887506217:ios:ec5ab8038751d595692938',
    messagingSenderId: '229887506217',
    projectId: 'event-manager-12814',
    storageBucket: 'event-manager-12814.appspot.com',
    iosBundleId: 'com.example.manejadorEventos',
  );
}
